INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Abdy', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Abdy', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Abdy', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Abdy', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Abdy', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Abdy', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Abdy', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Abdy', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Abdy', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Abdy', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Abdy', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Abdy', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Abdy', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Abdy', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Abdy', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Abdy', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Abdy', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Abdy', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Abdy', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Abdy', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Abdy', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Abdy', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Abdy', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Abdy', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Pietri', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Pietri', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Pietri', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Pietri', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Pietri', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Pietri', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Pietri', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Pietri', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Pietri', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Pietri', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Pietri', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Pietri', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Pietri', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Pietri', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Pietri', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Pietri', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Pietri', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Pietri', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Pietri', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Pietri', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Pietri', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Pietri', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Pietri', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Pietri', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Pietri', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Walklot', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Walklot', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Walklot', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Walklot', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Walklot', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Walklot', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Walklot', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Walklot', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Walklot', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Walklot', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Walklot', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Walklot', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Walklot', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Walklot', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Walklot', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Walklot', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Walklot', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Walklot', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Walklot', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Walklot', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Walklot', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Walklot', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Walklot', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Walklot', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Walklot', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Walklot', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Walklot', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Walklot', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Walklot', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Walklot', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Walklot', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Walklot', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Christoffels', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Christoffels', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Christoffels', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Christoffels', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Christoffels', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Christoffels', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Christoffels', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Christoffels', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Christoffels', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Christoffels', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Christoffels', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Christoffels', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Christoffels', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Christoffels', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Christoffels', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Christoffels', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Christoffels', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Christoffels', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Christoffels', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Christoffels', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Christoffels', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Christoffels', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Christoffels', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Christoffels', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Christoffels', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Christoffels', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Christoffels', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Christoffels', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Christoffels', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Christoffels', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Christoffels', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Christoffels', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Christoffels', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Christoffels', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Christoffels', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Christoffels', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Christoffels', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (119, 'Christoffels', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (119, 'Christoffels', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (120, 'Christoffels', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Treeby', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Treeby', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Treeby', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Treeby', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Treeby', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Treeby', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Treeby', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Treeby', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Treeby', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Treeby', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Treeby', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Treeby', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Treeby', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Treeby', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Treeby', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Treeby', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Treeby', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Treeby', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Treeby', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Treeby', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Treeby', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Wards', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Wards', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Wards', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Wards', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Wards', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Wards', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Wards', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Wards', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Wards', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Wards', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Wards', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Wards', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Wards', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Wards', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Wards', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Wards', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Wards', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Wards', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Wards', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Wards', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Wards', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Wards', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Wards', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Wards', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Wards', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Wards', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Wards', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Wards', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Wards', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Wards', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Wards', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Wards', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Vasnev', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Vasnev', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Vasnev', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Vasnev', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Vasnev', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Vasnev', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Vasnev', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Vasnev', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Vasnev', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Vasnev', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Fourmy', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Fourmy', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Fourmy', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Fourmy', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Fourmy', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Fourmy', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Fourmy', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Fourmy', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Fourmy', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Fourmy', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Fourmy', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Fourmy', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Fourmy', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Turford', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Turford', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Turford', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Turford', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Turford', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Turford', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Turford', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Turford', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Turford', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Turford', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Turford', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Turford', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Turford', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Turford', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Turford', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Turford', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Turford', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Turford', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Turford', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Turford', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Turford', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Turford', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Turford', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Turford', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Turford', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Turford', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Turford', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Turford', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Turford', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Turford', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Turford', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Turford', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Turford', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Turford', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Turford', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Turford', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Turford', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Turford', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Core', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Core', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Core', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Core', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Core', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Core', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Core', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Core', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Core', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Core', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Core', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Core', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Core', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Core', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Core', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Core', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Core', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Core', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Core', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Core', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Core', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Ricardou', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Ricardou', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Ricardou', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Ricardou', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Ricardou', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Ricardou', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Ricardou', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Ricardou', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Ricardou', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Ricardou', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Ricardou', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Ricardou', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Ricardou', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Ricardou', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Ricardou', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Ricardou', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Ricardou', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Ricardou', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Ricardou', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Ricardou', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Burnes', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Burnes', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Burnes', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Burnes', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Burnes', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Burnes', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Burnes', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Burnes', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Burnes', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Burnes', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Burnes', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Burnes', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Burnes', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Burnes', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Sotheron', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Sotheron', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Sotheron', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Sotheron', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Sotheron', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Sotheron', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Sotheron', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Sotheron', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Sotheron', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Sotheron', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Sotheron', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Sotheron', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Sotheron', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Sotheron', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Sotheron', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Sotheron', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Sotheron', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Sextie', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Sextie', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Sextie', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Sextie', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Sextie', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Sextie', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Sextie', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Sextie', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Sextie', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Sextie', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Sextie', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Sextie', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Sextie', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Sextie', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Sextie', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Sextie', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Sextie', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Sextie', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Sextie', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Sextie', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Sextie', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Sextie', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Sextie', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Sextie', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Sextie', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Sextie', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Sextie', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Sextie', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Thirwell', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Thirwell', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Thirwell', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Thirwell', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Thirwell', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Thirwell', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Thirwell', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Thirwell', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Thirwell', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Thirwell', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Thirwell', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Thirwell', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Thirwell', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Thirwell', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Thirwell', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Thirwell', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Thirwell', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Thirwell', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Thirwell', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Thirwell', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Thirwell', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Thirwell', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Thirwell', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Thirwell', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Thirwell', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Thirwell', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Thirwell', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Dominka', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Dominka', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Dominka', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Dominka', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Dominka', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Dominka', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Dominka', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Dominka', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Dominka', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Dominka', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Dominka', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Dominka', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Dominka', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Dominka', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Dominka', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Dominka', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Dominka', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Dominka', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Cragoe', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Cragoe', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Cragoe', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Cragoe', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Cragoe', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Cragoe', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Cragoe', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Cragoe', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Cragoe', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Cragoe', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Cragoe', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Cragoe', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Cragoe', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Cragoe', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Cragoe', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Cragoe', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Cragoe', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Cragoe', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Orfeur', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Orfeur', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Orfeur', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Orfeur', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Orfeur', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Orfeur', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Orfeur', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Orfeur', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Orfeur', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Orfeur', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Orfeur', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Orfeur', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Orfeur', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Orfeur', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Orfeur', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Orfeur', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Orfeur', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Orfeur', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'MacVaugh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'MacVaugh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'MacVaugh', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'MacVaugh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'MacVaugh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'MacVaugh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'MacVaugh', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'MacVaugh', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'MacVaugh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'MacVaugh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'MacVaugh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'MacVaugh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'MacVaugh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'MacVaugh', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'MacVaugh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'MacVaugh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'MacVaugh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'MacVaugh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'MacVaugh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'MacVaugh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'MacVaugh', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'MacVaugh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'MacVaugh', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'MacVaugh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'MacVaugh', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'MacVaugh', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'MacVaugh', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'MacVaugh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'MacVaugh', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Stannering', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Stannering', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Stannering', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Stannering', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Stannering', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Stannering', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Stannering', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Stannering', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Stoneham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Stoneham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Stoneham', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Stoneham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Stoneham', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Stoneham', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Stoneham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Stoneham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Stoneham', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Stoneham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Stoneham', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Stoneham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Stoneham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Stoneham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Stoneham', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Stoneham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Stoneham', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Stoneham', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Stoneham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Brunetti', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Brunetti', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Brunetti', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Brunetti', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Brunetti', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Brunetti', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Brunetti', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Brunetti', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Brunetti', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Brunetti', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Brunetti', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Brunetti', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Brunetti', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Brunetti', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Brunetti', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Brunetti', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Brunetti', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Brunetti', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Brunetti', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Brunetti', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Brunetti', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Martonfi', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Martonfi', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Martonfi', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Martonfi', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Martonfi', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Martonfi', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Martonfi', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Martonfi', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Martonfi', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Martonfi', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Martonfi', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Martonfi', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Martonfi', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Martonfi', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Martonfi', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Martonfi', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Butcher', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Butcher', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Butcher', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Butcher', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Butcher', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Butcher', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Butcher', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Butcher', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Butcher', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Butcher', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Butcher', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Butcher', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Butcher', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Butcher', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Butcher', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Butcher', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Butcher', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Butcher', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Butcher', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Butcher', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Butcher', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Butcher', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Butcher', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Butcher', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Butcher', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Butcher', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Butcher', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Butcher', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Butcher', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Butcher', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Butcher', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Butcher', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Butcher', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Butcher', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Butcher', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Butcher', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Butcher', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Butcher', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Butcher', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Butcher', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Maberley', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Maberley', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Maberley', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Maberley', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Maberley', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Maberley', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Maberley', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Maberley', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Maberley', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Maberley', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Maberley', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Maberley', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Maberley', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Maberley', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Maberley', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Maberley', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Maberley', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Maberley', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Maberley', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Maberley', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Maberley', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Maberley', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Alan', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Alan', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Alan', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Alan', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Alan', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Alan', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Alan', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Alan', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Alan', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Alan', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Alan', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Alan', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Alan', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Alan', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Alan', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Alan', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Alan', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Alan', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Alan', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Alan', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Alan', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Alan', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Alan', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Alan', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Alan', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Alan', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Alan', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Alan', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Alan', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Alan', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Alan', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Alan', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (119, 'Alan', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (119, 'Alan', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Dupre', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Dupre', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Dupre', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Dupre', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Dupre', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Dupre', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Dupre', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Dupre', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Dupre', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Dupre', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Dupre', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Dupre', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Merlin', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Merlin', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Merlin', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Merlin', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Merlin', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Merlin', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Merlin', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Merlin', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Merlin', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Merlin', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Merlin', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Merlin', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Merlin', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Merlin', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Merlin', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Merlin', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Merlin', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Merlin', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Merlin', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Merlin', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Merlin', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Merlin', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Merlin', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Merlin', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Merlin', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Merlin', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Merlin', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Merlin', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Merlin', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Merlin', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Merlin', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Merlin', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Merlin', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Merlin', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Schapero', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Schapero', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Schapero', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Schapero', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Schapero', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Schapero', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Schapero', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Schapero', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Schapero', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Schapero', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Schapero', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Schapero', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Schapero', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Schapero', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Schapero', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Schapero', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Schapero', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Schapero', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Schapero', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Schapero', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Schapero', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Schapero', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Schapero', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Schapero', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Schapero', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'MacAree', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'MacAree', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'MacAree', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'MacAree', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'MacAree', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'MacAree', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'MacAree', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'MacAree', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'MacAree', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'MacAree', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'MacAree', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'MacAree', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'MacAree', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'MacAree', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'MacAree', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'MacAree', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'MacAree', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'MacAree', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'MacAree', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'MacAree', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'MacAree', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'MacAree', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'MacAree', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'MacAree', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'MacAree', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'MacAree', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'MacAree', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'MacAree', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'MacAree', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'MacAree', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'MacAree', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'MacAree', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'MacAree', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'MacAree', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'MacAree', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'MacAree', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'MacAree', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'MacAree', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'MacAree', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'MacAree', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'MacAree', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'MacAree', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Drabble', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Drabble', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Drabble', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Drabble', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Drabble', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Drabble', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Drabble', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Drabble', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Drabble', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Drabble', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Drabble', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Drabble', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Drabble', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Drabble', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Drabble', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Drabble', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Drabble', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Storrar', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Storrar', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Storrar', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Storrar', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Storrar', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Storrar', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Storrar', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Storrar', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Storrar', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Storrar', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Storrar', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Storrar', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Storrar', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Storrar', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Storrar', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Storrar', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Storrar', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Storrar', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Carlick', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Carlick', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Carlick', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Carlick', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Carlick', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Carlick', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Carlick', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Carlick', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Carlick', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Carlick', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Carlick', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Carlick', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Carlick', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Sorrel', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Sorrel', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Sorrel', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Sorrel', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Sorrel', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Sorrel', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Sorrel', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Sorrel', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Sorrel', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Sorrel', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Sorrel', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Sorrel', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Sorrel', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Sorrel', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Sorrel', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Sorrel', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Sorrel', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Sorrel', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Sorrel', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Sorrel', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Sorrel', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Sorrel', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Sorrel', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Sorrel', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Sorrel', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Fasey', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Fasey', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Fasey', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Fasey', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Fasey', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Fasey', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Fasey', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Fasey', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Fasey', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Fasey', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Fasey', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Fasey', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Fasey', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Fasey', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Fasey', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Fasey', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Fasey', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Fasey', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Fasey', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Fasey', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Fasey', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Fasey', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Fasey', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Birdfield', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Birdfield', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Birdfield', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Birdfield', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Birdfield', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Birdfield', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Birdfield', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Birdfield', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Birdfield', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Birdfield', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Birdfield', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Birdfield', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Birdfield', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Birdfield', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Birdfield', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Birdfield', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Birdfield', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Birdfield', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Birdfield', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Birdfield', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Birdfield', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Birdfield', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Birdfield', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Birdfield', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Birdfield', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Birdfield', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Birdfield', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Birdfield', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Birdfield', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Birdfield', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'Birdfield', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (119, 'Birdfield', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (119, 'Birdfield', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (119, 'Birdfield', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Clementucci', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Clementucci', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Clementucci', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Clementucci', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Clementucci', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Clementucci', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Clementucci', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Clementucci', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Clementucci', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Clementucci', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Clementucci', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Clementucci', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Clementucci', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Clementucci', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Clementucci', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Clementucci', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Clementucci', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Le Fleming', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Le Fleming', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Le Fleming', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Le Fleming', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Le Fleming', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Le Fleming', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Le Fleming', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Le Fleming', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Le Fleming', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Le Fleming', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Le Fleming', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Le Fleming', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Le Fleming', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Le Fleming', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Le Fleming', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Le Fleming', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Le Fleming', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Le Fleming', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Le Fleming', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Le Fleming', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Le Fleming', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Le Fleming', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Le Fleming', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Le Fleming', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Le Fleming', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Le Fleming', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'Le Fleming', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'Le Fleming', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'MacKeogh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'MacKeogh', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'MacKeogh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'MacKeogh', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'MacKeogh', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'MacKeogh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'MacKeogh', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'MacKeogh', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'MacKeogh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'MacKeogh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'MacKeogh', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'MacKeogh', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'MacKeogh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'MacKeogh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'MacKeogh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'MacKeogh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'MacKeogh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'MacKeogh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'MacKeogh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'MacKeogh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'MacKeogh', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'MacKeogh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'MacKeogh', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'MacKeogh', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'MacKeogh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'MacKeogh', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'MacKeogh', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'MacKeogh', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'MacKeogh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'MacKeogh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'MacKeogh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'MacKeogh', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'MacKeogh', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'MacKeogh', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'MacKeogh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'MacKeogh', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (116, 'MacKeogh', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (117, 'MacKeogh', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (118, 'MacKeogh', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Grayham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (101, 'Grayham', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Grayham', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Grayham', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (102, 'Grayham', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Grayham', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Grayham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (103, 'Grayham', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Grayham', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (104, 'Grayham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (105, 'Grayham', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Grayham', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (106, 'Grayham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Grayham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Grayham', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (107, 'Grayham', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Grayham', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Grayham', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (108, 'Grayham', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Grayham', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (109, 'Grayham', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Grayham', 'tv');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Grayham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (110, 'Grayham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Grayham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (111, 'Grayham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (112, 'Grayham', 'ac');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (113, 'Grayham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Grayham', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Grayham', 'fridge');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (114, 'Grayham', 'patio');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Grayham', 'safe');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Grayham', 'hot tub');
INSERT INTO HasCommodite (numeroChambre, nomHotel, commodite) VALUES (115, 'Grayham', 'tv');
