# Generated by Django 5.0.4 on 2024-04-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beapp', '0002_hotel_nombrechambre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='nombreChambre',
            new_name='nombrechambre',
        ),
    ]
