# Generated by Django 5.0.4 on 2024-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='nombreChambre',
            field=models.IntegerField(null=True),
        ),
    ]
