# Generated by Django 5.0.2 on 2024-04-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapp', '0003_rename_nombrechambre_hotel_nombrechambre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hascommodite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hascommodite',
            name='nomhotel',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='beapp.hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='hascommodite',
            unique_together={('numerochambre', 'commodite', 'nomhotel')},
        ),
    ]
